# Generated by Django 5.0 on 2024-05-27 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('idGenero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='MuchachoStore.genero')),
            ],
        ),
    ]
