# Generated by Django 4.1.2 on 2024-07-17 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MuchachoStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='id_genero',
            field=models.AutoField(db_column='Genero', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idGenero',
            field=models.ForeignKey(db_column='Genero', on_delete=django.db.models.deletion.CASCADE, to='MuchachoStore.genero'),
        ),
    ]
