# Generated by Django 5.0 on 2024-05-27 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuchachoStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idGenero',
            field=models.ForeignKey(db_column='Genero', on_delete=django.db.models.deletion.CASCADE, to='MuchachoStore.genero'),
        ),
    ]
