# Generated by Django 5.0 on 2024-05-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuchachoStore', '0002_alter_usuario_idgenero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='id_genero',
            field=models.AutoField(db_column='Genero', primary_key=True, serialize=False),
        ),
    ]
